### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by doyubkim** [utilForever/CubbyFlow-demo#1]
(I know you just created this repo, but since the matter is important..)

This repo is again copied from fluid-engine-dev-demo. Please mention that clearly in the readme or use GitHub’s Fork functionality. Also, the last paragraph is a dedicated statement for Jet Framework and related repos only. Please use your own sentences.

**Comment by utilForever** [comment]
Thank you for your feedback. I will reflect on today.

**Comment by utilForever** [comment]
@doyubkim I updated README. Please check it. :^)

**Comment by doyubkim** [comment]
Thanks!
